// <auto-generated />
using System;
using CinemaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaApi.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaApi.Models.Entities.DisponibilidadSalaResult", b =>
                {
                    b.Property<int>("CantidadPeliculas")
                        .HasColumnType("int");

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("CinemaApi.Models.Entities.Pelicula", b =>
                {
                    b.Property<int>("IdPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pelicula");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPelicula"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("Duracion")
                        .HasColumnType("int")
                        .HasColumnName("duracion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPelicula");

                    b.ToTable("pelicula", (string)null);

                    b.HasData(
                        new
                        {
                            IdPelicula = 1,
                            Activo = true,
                            Duracion = 143,
                            Nombre = "Avengers"
                        },
                        new
                        {
                            IdPelicula = 2,
                            Activo = true,
                            Duracion = 152,
                            Nombre = "Batman"
                        },
                        new
                        {
                            IdPelicula = 3,
                            Activo = true,
                            Duracion = 143,
                            Nombre = "Superman"
                        },
                        new
                        {
                            IdPelicula = 4,
                            Activo = true,
                            Duracion = 121,
                            Nombre = "Spiderman"
                        },
                        new
                        {
                            IdPelicula = 5,
                            Activo = true,
                            Duracion = 126,
                            Nombre = "Iron Man"
                        });
                });

            modelBuilder.Entity("CinemaApi.Models.Entities.PeliculaSalaCine", b =>
                {
                    b.Property<int>("IdPeliculaSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pelicula_sala");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeliculaSala"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaPublicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_publicacion");

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int")
                        .HasColumnName("id_pelicula");

                    b.Property<int>("IdSalaCine")
                        .HasColumnType("int")
                        .HasColumnName("id_sala_cine");

                    b.HasKey("IdPeliculaSala");

                    b.HasIndex("IdPelicula");

                    b.HasIndex("IdSalaCine");

                    b.ToTable("pelicula_salacine", (string)null);

                    b.HasData(
                        new
                        {
                            IdPeliculaSala = 1,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 25),
                            IdPelicula = 1,
                            IdSalaCine = 1
                        },
                        new
                        {
                            IdPeliculaSala = 2,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 25),
                            IdPelicula = 2,
                            IdSalaCine = 1
                        },
                        new
                        {
                            IdPeliculaSala = 3,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 26),
                            IdPelicula = 1,
                            IdSalaCine = 2
                        },
                        new
                        {
                            IdPeliculaSala = 4,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 26),
                            IdPelicula = 2,
                            IdSalaCine = 2
                        },
                        new
                        {
                            IdPeliculaSala = 5,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 26),
                            IdPelicula = 3,
                            IdSalaCine = 2
                        },
                        new
                        {
                            IdPeliculaSala = 6,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 26),
                            IdPelicula = 4,
                            IdSalaCine = 2
                        },
                        new
                        {
                            IdPeliculaSala = 7,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 27),
                            IdPelicula = 1,
                            IdSalaCine = 3
                        },
                        new
                        {
                            IdPeliculaSala = 8,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 27),
                            IdPelicula = 2,
                            IdSalaCine = 3
                        },
                        new
                        {
                            IdPeliculaSala = 9,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 27),
                            IdPelicula = 3,
                            IdSalaCine = 3
                        },
                        new
                        {
                            IdPeliculaSala = 10,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 27),
                            IdPelicula = 4,
                            IdSalaCine = 3
                        },
                        new
                        {
                            IdPeliculaSala = 11,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 27),
                            IdPelicula = 5,
                            IdSalaCine = 3
                        },
                        new
                        {
                            IdPeliculaSala = 12,
                            Activo = true,
                            FechaFin = new DateOnly(2026, 9, 15),
                            FechaPublicacion = new DateOnly(2026, 8, 27),
                            IdPelicula = 1,
                            IdSalaCine = 3
                        });
                });

            modelBuilder.Entity("CinemaApi.Models.Entities.SalaCine", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sala");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSala"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("IdSala");

                    b.ToTable("sala_cine", (string)null);

                    b.HasData(
                        new
                        {
                            IdSala = 1,
                            Estado = true,
                            Nombre = "Sala 1"
                        },
                        new
                        {
                            IdSala = 2,
                            Estado = true,
                            Nombre = "Sala 2"
                        },
                        new
                        {
                            IdSala = 3,
                            Estado = true,
                            Nombre = "Sala VIP"
                        });
                });

            modelBuilder.Entity("CinemaApi.Models.Entities.PeliculaSalaCine", b =>
                {
                    b.HasOne("CinemaApi.Models.Entities.Pelicula", "Pelicula")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdPelicula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaApi.Models.Entities.SalaCine", "SalaCine")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdSalaCine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("SalaCine");
                });

            modelBuilder.Entity("CinemaApi.Models.Entities.Pelicula", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("CinemaApi.Models.Entities.SalaCine", b =>
                {
                    b.Navigation("Asignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
